#
# Copyright (C) 2020 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

BOARD_VENDOR := realme
DEVICE_PATH := device/realme/samurai

# --- [STAGE 1] ARCHITECTURE OPTIMIZATION (Kryo 485 Beast) ---
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a-dotprod
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := kryo485
TARGET_CPU_VARIANT_RUNTIME := kryo485

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := kryo485
TARGET_2ND_CPU_VARIANT_RUNTIME := kryo485

TARGET_OTA_ASSERT_DEVICE := samurai,RMX1931,RMX1931L1

# --- [STAGE 2] KERNEL & EXTREME BOOT COMMANDS ---
BOARD_BOOTIMG_HEADER_VERSION := 1
BOARD_MKBOOTIMG_ARGS := --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_CMDLINE := \
    androidboot.boot_devices=soc/1d84000.ufshc \
    androidboot.console=ttyMSM0 \
    androidboot.hardware=qcom \
    androidboot.usbcontroller=a600000.dwc3 \
    kpti=off \
    loop.max_part=7 \
    msm_rtb.filter=0x237 \
    service_locator.enable=1 \
    swiotlb=2048 \
    cgroup_disable=pressure \
    androidboot.memcg=1 \
    lpm_levels.sleep_disabled=1 \
    androidboot.perf_mode=1 \
    video=vfb:640x400,bpp=32,memsize=3072000

BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_SEPARATED_DTBO := true
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_RAMDISK_USE_LZ4 := true

# কার্নেল কনফিগারেশন পাথ চেক (vendor/debugfs.config যদি না থাকে তবে শুধু defconfig রাখো)
TARGET_KERNEL_CONFIG := samurai_defconfig
TARGET_KERNEL_SOURCE := kernel/realme/sm8150

# --- [STAGE 3] DISPLAY, GPU & VULKAN TURBO ---
# গ্রাফিক্সের সর্বোচ্চ পারফরম্যান্সের জন্য
MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 2048*1024
MAX_VIRTUAL_DISPLAY_DIMENSION := 4096
TARGET_DISABLED_UBWC := false
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
TARGET_SCREEN_DENSITY := 480
TARGET_USES_DISPLAY_RENDER_INTENTS := true
TARGET_USES_DRM_PP := true
TARGET_USES_GRALLOC4 := true
TARGET_USES_HWC2 := true
TARGET_USES_ION := true
TARGET_HAS_HDR_DISPLAY := true
TARGET_HAS_WIDE_COLOR_DISPLAY := true
BOARD_USES_ADRENO := true
TARGET_USES_NEW_ION_API := true
BOARD_USES_VULKAN := true
TARGET_USES_VULKAN := true

# --- [STAGE 4] EXTREME SYSTEM & MEMORY TUNING ---
BOARD_USES_QCOM_HARDWARE := true
TARGET_USES_INTERACTION_BOOST := true
MALLOC_SVELTE := false
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_USES_BUILD_COPY_HEADERS := true

# Partitions (Strict Non-Dynamic for OrangeFox)
BOARD_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 83886080
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_DTBOIMG_PARTITION_SIZE := 25165824
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 4487905280
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_ODMIMAGE_PARTITION_SIZE := 268435456
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_PARTITION_SIZE := 1649410048
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 262144
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# WiFi
BOARD_WLAN_DEVICE := qcwcn
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
WIFI_DRIVER_DEFAULT := qca_cld3
WPA_SUPPLICANT_VERSION := VER_0_8_X

# SEPolicy (বুট লুপ এড়াতে এটি মাস্ট)
BOARD_VENDOR_SEPOLICY_DIRS += device/realme/samurai/sepolicy/vendor
SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += device/realme/samurai/sepolicy/private

# --- [FINAL] VENDOR INHERITANCE ---
include vendor/realme/samurai/BoardConfigVendor.mk
